### ISSUE TITLE
Serve kpow under subpath

### ISSUE THREAD

**Issue by miguel-cardoso-mindera** [operatr-io/kpow-helm-charts#8]
Hello, I'm deploying kpow on my kubernetes cluster like this:

```
image:
  repository: factorhouse/kpow-ce
  tag: 91.4.1
env:
  LICENSE_ID: "XXXXXXXXXXXXXXXXXXXXXXX"
  LICENSE_CODE: "KPOW_COMMUNITY"
  LICENSEE: "XXXX"
  LICENSE_EXPIRY: "2024-05-31"
  LICENSE_SIGNATURE: "XXXXXXXXXXXXXXXXXXXXXXX"
  BOOTSTRAP: "http://cluster-kafka-bootstrap.kafka:9092"
  SECURITY_PROTOCOL: "PLAINTEXT"
  SASL_MECHANISM: "PLAIN"
  LICENSE_CREDITS: "1"

  SCHEMA_REGISTRY_URL: "http://schema-registry.kafka:8081"
  SCHEMA_REGISTRY_NAME: "schema-registry"
```

And if I port-forward the kpow pod, I can access the UI just fine.

However I want to present this under an api-gateway, so that people can access kpow under `https://my-api-gateway.com/kpow` but I do not see how I can make this possible.

Is this a feature that currently exists?
